apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 192.168.0.33/devops/cicd-web-project
  newTag: newest
- name: 192.168.0.41/devops/cicd-web-project
  newTag: "11"
- name: 192.168.0.41/devops/cicd-web-project:11
  newTag: latest
resources:
- ../base-kustomize
